### ISSUE TITLE
404 to Process Journal

### ISSUE THREAD

**Issue by gregsadetsky** [pippinbarr/pippinbarr.github.io#1]
hey! (it's been a while!)

just wanted to point out that the first link on:

https://pippinbarr.com/super-mario-nothing/process/

i.e. "Process Journal" links to a 404 page -> https://pippinbarr.com/super-mario-nothing/process/process-journal.md

I'm not ... sure where the above /process/ source .md page is (as in -- it should be in this repo? but I can't find it) so I can't point to the wrong line and submit a PR. sorry! but hopefully/undoubtedly you'll know! :-)

cheers

**Comment by pippinbarr** [comment]
Thanks Greg - fixed with this https://github.com/pippinbarr/super-mario-nothing/commit/d6e043a31b52628c96324fd7cf9e4b4de51645ad

The confusion is because I point my domain at my GitHub Pages presence and an offshoot of that (which I didn't actually predict initially) is that *all* of my repos become subfolders of my domain. So pippinbarr.com/super-mario-nothing is actually pointing into my super-mario-nothing repo.

**Comment by gregsadetsky** [comment]
makes sense, thank you! I'm reading _The Stuff Games Are Made Of_ by the way, just to explain why I'm going through your past publications & games :-) have a great one

**Comment by pippinbarr** [comment]
Haha - thanks! Let me know what you think if you want!
